[[backends]]
  group = "tech-feeds-apis-0-0-1"
  url_pattern = "/api/35/feeds/tech"
  method = "GET"
  encoding = "json"
  host = ["https://api.apitore.com"]
  whitelist = ["endTime", "entries", "lastUpdatedAt", "log", "num", "page", "processTime", "startTime"]
  concurrent_calls = 1
  [backends.extra_config]
    provider = "apitore.com"
    description = "Various tech feeds.<BR />[Endpoint] https://api.apitore.com/api/35"
    version = "0.0.1"
    slug = "tech-feeds-apis-0-0-1-api-35-feeds-tech"
    schemes = ["https"]
    consumes = ["json"]
    produces = ["json"]
    hosts = ["https://api.apitore.com"]
    [backends.extra_config.mapping]
      endTime = "endTime"
      entries = "entries"
      lastUpdatedAt = "lastUpdatedAt"
      log = "log"
      num = "num"
      page = "page"
      processTime = "processTime"
      startTime = "startTime"
