[[backends]]
  group = "siterecoverymanagementclient-2016-08-10"
  url_pattern = "/Subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft"
  method = "RECOVERYSERVICES/OPERATIONS"
  encoding = "json"
  host = ["https://management.azure.com"]
  concurrent_calls = 1
  [backends.extra_config]
    provider = "azure.com"
    version = "2016-08-10"
    slug = "siterecoverymanagementclient-2016-08-10-subscriptions-subscriptionid-resourcegroups-resourcegroupname-providers-microsoft"
    schemes = ["https"]
    consumes = ["json"]
    produces = ["json"]
    hosts = ["https://management.azure.com"]
    topics = ["cloud"]
