[[backends]]
  group = "import-io-1-0"
  url_pattern = "/extractor/{extractorId}"
  method = "GET"
  encoding = "json;charset=UTF-8"
  host = ["https://extraction.import.io"]
  url_keys = ["extractorId"]
  query_string_params = ["url"]
  whitelist = ["error", "exceptionType", "extractorData", "pageData", "runtimeConfigId", "sequenceNumber", "timestamp", "url"]
  concurrent_calls = 1
  [backends.extra_config]
    provider = "import.io"
    version = "1.0"
    slug = "import-io-1-0-extractor-extractorid"
    schemes = ["https"]
    produces = ["json;charset=UTF-8"]
    hosts = ["https://extraction.import.io"]
    topics = ["extraction-import-io", "tools"]
    [backends.extra_config.mapping]
      error = "error"
      exceptionType = "exceptionType"
      extractorData = "extractorData"
      pageData = "pageData"
      runtimeConfigId = "runtimeConfigId"
      sequenceNumber = "sequenceNumber"
      timestamp = "timestamp"
      url = "url"
