[[backends]]
  group = "azure-ml-web-services-management-client-2016-05-01-preview"
  url_pattern = "/subscriptions/{subscriptionId}/providers/Microsoft"
  method = "MACHINELEARNING/WEBSERVICES"
  encoding = "json"
  host = ["https://management.azure.com"]
  concurrent_calls = 1
  [backends.extra_config]
    provider = "azure.com"
    description = "These APIs allow end users to operate on Azure Machine Learning Web Services resources. They support the following operations:<ul><li>Create or update a web service</li><li>Get a web service</li><li>Patch a web service</li><li>Delete a web service</li><li>Get All Web Services in a Resource Group </li><li>Get All Web Services in a Subscription</li><li>Get Web Services Keys</li></ul>"
    version = "2016-05-01-preview"
    slug = "azure-ml-web-services-management-client-2016-05-01-preview-subscriptions-subscriptionid-providers-microsoft"
    schemes = ["https"]
    consumes = ["json", "json"]
    produces = ["json", "json"]
    hosts = ["https://management.azure.com"]
    topics = ["machine-learning"]

[[backends]]
  group = "azure-ml-web-services-management-client-2016-05-01-preview"
  url_pattern = "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft"
  method = "MACHINELEARNING/WEBSERVICES"
  encoding = "json"
  host = ["https://management.azure.com"]
  concurrent_calls = 1
  [backends.extra_config]
    provider = "azure.com"
    description = "These APIs allow end users to operate on Azure Machine Learning Web Services resources. They support the following operations:<ul><li>Create or update a web service</li><li>Get a web service</li><li>Patch a web service</li><li>Delete a web service</li><li>Get All Web Services in a Resource Group </li><li>Get All Web Services in a Subscription</li><li>Get Web Services Keys</li></ul>"
    version = "2016-05-01-preview"
    slug = "azure-ml-web-services-management-client-2016-05-01-preview-subscriptions-subscriptionid-resourcegroups-resourcegroupname-providers-microsoft"
    schemes = ["https"]
    consumes = ["json", "json"]
    produces = ["json", "json"]
    hosts = ["https://management.azure.com"]
    topics = ["machine-learning"]
