[[backends]]
  group = "engagement-managementclient-2014-12-01"
  url_pattern = "/subscriptions/{subscriptionId}/providers/Microsoft"
  method = "MOBILEENGAGEMENT/APPCOLLECTIONS"
  encoding = "json"
  host = ["https://management.azure.com"]
  concurrent_calls = 1
  [backends.extra_config]
    provider = "azure.com"
    description = "Microsoft Azure Mobile Engagement REST APIs."
    version = "2014-12-01"
    slug = "engagement-managementclient-2014-12-01-subscriptions-subscriptionid-providers-microsoft"
    schemes = ["https"]
    consumes = ["json"]
    produces = ["json"]
    hosts = ["https://management.azure.com"]
    topics = ["analytics", "cloud", "marketing"]

[[backends]]
  group = "engagement-managementclient-2014-12-01"
  url_pattern = "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft"
  method = "MOBILEENGAGEMENT/APPCOLLECTIONS/{APPCOLLECTION}/APPS"
  encoding = "json"
  host = ["https://management.azure.com"]
  concurrent_calls = 1
  [backends.extra_config]
    provider = "azure.com"
    description = "Microsoft Azure Mobile Engagement REST APIs."
    version = "2014-12-01"
    slug = "engagement-managementclient-2014-12-01-subscriptions-subscriptionid-resourcegroups-resourcegroupname-providers-microsoft"
    schemes = ["https"]
    consumes = ["json"]
    produces = ["json"]
    hosts = ["https://management.azure.com"]
    topics = ["analytics", "cloud", "marketing"]
