[[backends]]
  group = "freesound-2-0-0"
  url_pattern = "/apiv2/search/text"
  method = "GET"
  encoding = "xml"
  host = ["http://www.freesound.org"]
  concurrent_calls = 1
  [backends.extra_config]
    provider = "freesound.org"
    description = "With the Freesound APIv2 you can browse, search, and retrieve information about Freesound users, packs, and the sounds themselves of course. You can find similar sounds to a given target (based on content analysis) and retrieve automatically extracted features from audio files, as well as perform advanced queries combining content analysis features and other metadata (tags, etc...). With the Freesound APIv2, you can also upload, comment, rate and bookmark sounds!"
    version = "2.0.0"
    slug = "freesound-2-0-0-apiv2-search-text"
    schemes = ["http"]
    produces = ["xml", "json"]
    hosts = ["http://www.freesound.org"]
    topics = ["media"]

[[backends]]
  group = "freesound-2-0-0"
  url_pattern = "/apiv2/sounds/{soundId}"
  method = "GET"
  encoding = "xml"
  host = ["http://www.freesound.org"]
  whitelist = ["id", "name", "url"]
  concurrent_calls = 1
  [backends.extra_config]
    provider = "freesound.org"
    description = "With the Freesound APIv2 you can browse, search, and retrieve information about Freesound users, packs, and the sounds themselves of course. You can find similar sounds to a given target (based on content analysis) and retrieve automatically extracted features from audio files, as well as perform advanced queries combining content analysis features and other metadata (tags, etc...). With the Freesound APIv2, you can also upload, comment, rate and bookmark sounds!"
    version = "2.0.0"
    slug = "freesound-2-0-0-apiv2-sounds-soundid"
    schemes = ["http"]
    produces = ["xml", "json"]
    hosts = ["http://www.freesound.org"]
    topics = ["media"]
    [backends.extra_config.mapping]
      id = "id"
      name = "name"
      url = "url"
