[[backends]]
  group = "import-io-1-0"
  url_pattern = "/extractor/{extractorId}/runs"
  method = "GET"
  encoding = "xml"
  host = ["https://rss.import.io"]
  url_keys = ["extractorId"]
  concurrent_calls = 1
  [backends.extra_config]
    provider = "import.io"
    version = "1.0"
    slug = "import-io-1-0-extractor-extractorid-runs"
    schemes = ["https"]
    produces = ["xml"]
    hosts = ["https://rss.import.io"]
    topics = ["rss-import-io", "tools"]
