[[backends]]
  group = "dnsmanagementclient-2016-04-01"
  url_pattern = "/subscriptions/{subscriptionId}/providers/Microsoft"
  method = "NETWORK/DNSZONES"
  encoding = "json"
  host = ["https://management.azure.com"]
  concurrent_calls = 1
  [backends.extra_config]
    provider = "azure.com"
    description = "The DNS Management Client."
    version = "2016-04-01"
    slug = "dnsmanagementclient-2016-04-01-subscriptions-subscriptionid-providers-microsoft"
    schemes = ["https"]
    consumes = ["json"]
    produces = ["json"]
    hosts = ["https://management.azure.com"]
    topics = ["cloud", "hosting"]

[[backends]]
  group = "dnsmanagementclient-2016-04-01"
  url_pattern = "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft"
  method = "NETWORK/DNSZONES"
  encoding = "json"
  host = ["https://management.azure.com"]
  concurrent_calls = 1
  [backends.extra_config]
    provider = "azure.com"
    description = "The DNS Management Client."
    version = "2016-04-01"
    slug = "dnsmanagementclient-2016-04-01-subscriptions-subscriptionid-resourcegroups-resourcegroupname-providers-microsoft"
    schemes = ["https"]
    consumes = ["json"]
    produces = ["json"]
    hosts = ["https://management.azure.com"]
    topics = ["cloud", "hosting"]
