[[backends]]
  group = "logicmanagementclient-2016-06-01"
  url_pattern = "/providers/Microsoft"
  method = "LOGIC/OPERATIONS"
  encoding = "json"
  host = ["https://management.azure.com"]
  concurrent_calls = 1
  [backends.extra_config]
    provider = "azure.com"
    description = "REST API for Azure Logic Apps."
    version = "2016-06-01"
    slug = "logicmanagementclient-2016-06-01-providers-microsoft"
    schemes = ["https"]
    consumes = ["json"]
    produces = ["json"]
    hosts = ["https://management.azure.com"]
    topics = ["cloud", "developer-tools"]

[[backends]]
  group = "logicmanagementclient-2016-06-01"
  url_pattern = "/subscriptions/{subscriptionId}/providers/Microsoft"
  method = "LOGIC/INTEGRATIONACCOUNTS"
  encoding = "json"
  host = ["https://management.azure.com"]
  concurrent_calls = 1
  [backends.extra_config]
    provider = "azure.com"
    description = "REST API for Azure Logic Apps."
    version = "2016-06-01"
    slug = "logicmanagementclient-2016-06-01-subscriptions-subscriptionid-providers-microsoft"
    schemes = ["https"]
    consumes = ["json"]
    produces = ["json"]
    hosts = ["https://management.azure.com"]
    topics = ["cloud", "developer-tools"]

[[backends]]
  group = "logicmanagementclient-2016-06-01"
  url_pattern = "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft"
  method = "LOGIC/INTEGRATIONACCOUNTS"
  encoding = "json"
  host = ["https://management.azure.com"]
  concurrent_calls = 1
  [backends.extra_config]
    provider = "azure.com"
    description = "REST API for Azure Logic Apps."
    version = "2016-06-01"
    slug = "logicmanagementclient-2016-06-01-subscriptions-subscriptionid-resourcegroups-resourcegroupname-providers-microsoft"
    schemes = ["https"]
    consumes = ["json"]
    produces = ["json"]
    hosts = ["https://management.azure.com"]
    topics = ["cloud", "developer-tools"]
