[[backends]]
  group = "aws-mobile-2017-07-01"
  url_pattern = "/bundles"
  method = "GET"
  encoding = "json"
  host = ["http://mobile.amazonaws.com"]
  query_string_params = ["maxResults", "nextToken"]
  concurrent_calls = 1
  [backends.extra_config]
    provider = "amazonaws.com"
    description = " AWS Mobile Service provides mobile app and website developers with capabilities required to configure AWS resources and bootstrap their developer desktop projects with the necessary SDKs, constants, tools and samples to make use of those resources. "
    version = "2017-07-01"
    slug = "aws-mobile-2017-07-01-bundles"
    schemes = ["http"]
    consumes = ["json"]
    produces = ["json"]
    hosts = ["http://mobile.amazonaws.com"]
    topics = ["cloud"]

[[backends]]
  group = "aws-mobile-2017-07-01"
  url_pattern = "/bundles/{bundleId}"
  method = "POST"
  encoding = "json"
  host = ["http://mobile.amazonaws.com"]
  url_keys = ["bundleId"]
  concurrent_calls = 1
  [backends.extra_config]
    provider = "amazonaws.com"
    description = " AWS Mobile Service provides mobile app and website developers with capabilities required to configure AWS resources and bootstrap their developer desktop projects with the necessary SDKs, constants, tools and samples to make use of those resources. "
    version = "2017-07-01"
    slug = "aws-mobile-2017-07-01-bundles-bundleid"
    schemes = ["http"]
    consumes = ["json"]
    produces = ["json"]
    hosts = ["http://mobile.amazonaws.com"]
    topics = ["cloud"]

[[backends]]
  group = "aws-mobile-2017-07-01"
  url_pattern = "/exports/{projectId}"
  method = "POST"
  encoding = "json"
  host = ["http://mobile.amazonaws.com"]
  url_keys = ["projectId"]
  query_string_params = ["projectId"]
  concurrent_calls = 1
  [backends.extra_config]
    provider = "amazonaws.com"
    description = " AWS Mobile Service provides mobile app and website developers with capabilities required to configure AWS resources and bootstrap their developer desktop projects with the necessary SDKs, constants, tools and samples to make use of those resources. "
    version = "2017-07-01"
    slug = "aws-mobile-2017-07-01-exports-projectid"
    schemes = ["http"]
    consumes = ["json"]
    produces = ["json"]
    hosts = ["http://mobile.amazonaws.com"]
    topics = ["cloud"]

[[backends]]
  group = "aws-mobile-2017-07-01"
  url_pattern = "/project"
  method = "GET"
  encoding = "json"
  host = ["http://mobile.amazonaws.com"]
  concurrent_calls = 1
  [backends.extra_config]
    provider = "amazonaws.com"
    description = " AWS Mobile Service provides mobile app and website developers with capabilities required to configure AWS resources and bootstrap their developer desktop projects with the necessary SDKs, constants, tools and samples to make use of those resources. "
    version = "2017-07-01"
    slug = "aws-mobile-2017-07-01-project"
    schemes = ["http"]
    consumes = ["json"]
    produces = ["json"]
    hosts = ["http://mobile.amazonaws.com"]
    topics = ["cloud"]

[[backends]]
  group = "aws-mobile-2017-07-01"
  url_pattern = "/projects"
  method = "GET"
  encoding = "json"
  host = ["http://mobile.amazonaws.com"]
  query_string_params = ["maxResults", "nextToken"]
  concurrent_calls = 1
  [backends.extra_config]
    provider = "amazonaws.com"
    description = " AWS Mobile Service provides mobile app and website developers with capabilities required to configure AWS resources and bootstrap their developer desktop projects with the necessary SDKs, constants, tools and samples to make use of those resources. "
    version = "2017-07-01"
    slug = "aws-mobile-2017-07-01-projects"
    schemes = ["http"]
    consumes = ["json"]
    produces = ["json"]
    hosts = ["http://mobile.amazonaws.com"]
    topics = ["cloud"]

[[backends]]
  group = "aws-mobile-2017-07-01"
  url_pattern = "/update"
  method = "POST"
  encoding = "json"
  host = ["http://mobile.amazonaws.com"]
  concurrent_calls = 1
  [backends.extra_config]
    provider = "amazonaws.com"
    description = " AWS Mobile Service provides mobile app and website developers with capabilities required to configure AWS resources and bootstrap their developer desktop projects with the necessary SDKs, constants, tools and samples to make use of those resources. "
    version = "2017-07-01"
    slug = "aws-mobile-2017-07-01-update"
    schemes = ["http"]
    consumes = ["json"]
    produces = ["json"]
    hosts = ["http://mobile.amazonaws.com"]
    topics = ["cloud"]
