[[backends]]
  group = "apimatic-api-transformer-1-0"
  url_pattern = "/api/transform/transform"
  method = "POST"
  encoding = "json"
  host = ["https://apimatic.io"]
  concurrent_calls = 1
  [backends.extra_config]
    provider = "apimatic.io"
    description = "Transform API Descriptions from/to various formats"
    version = "1.0"
    slug = "apimatic-api-transformer-1-0-api-transform-transform"
    schemes = ["https"]
    consumes = ["x-www-form-urlencoded", "plain", "form-data"]
    produces = ["json", "x-yaml"]
    hosts = ["https://apimatic.io"]
    topics = ["developer-tools", "tools"]
