[[backends]]
  group = "amazon-dynamodb-streams-2012-08-10"
  url_pattern = "/#GetRecords"
  method = "POST"
  encoding = "json"
  host = ["http://streams.dynamodb.amazonaws.com"]
  concurrent_calls = 1
  [backends.extra_config]
    provider = "amazonaws.com"
    description = "<fullname>Amazon DynamoDB</fullname> <p>Amazon DynamoDB Streams provides API actions for accessing streams and processing stream records. To learn more about application development with Streams, see <a href=\"http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Streams.html\">Capturing Table Activity with DynamoDB Streams</a> in the Amazon DynamoDB Developer Guide.</p>"
    version = "2012-08-10"
    slug = "amazon-dynamodb-streams-2012-08-10-getrecords"
    schemes = ["http"]
    consumes = ["json"]
    produces = ["json"]
    hosts = ["http://streams.dynamodb.amazonaws.com"]
    topics = ["cloud"]

[[backends]]
  group = "amazon-dynamodb-streams-2012-08-10"
  url_pattern = "/#GetShardIterator"
  method = "POST"
  encoding = "json"
  host = ["http://streams.dynamodb.amazonaws.com"]
  concurrent_calls = 1
  [backends.extra_config]
    provider = "amazonaws.com"
    description = "<fullname>Amazon DynamoDB</fullname> <p>Amazon DynamoDB Streams provides API actions for accessing streams and processing stream records. To learn more about application development with Streams, see <a href=\"http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Streams.html\">Capturing Table Activity with DynamoDB Streams</a> in the Amazon DynamoDB Developer Guide.</p>"
    version = "2012-08-10"
    slug = "amazon-dynamodb-streams-2012-08-10-getsharditerator"
    schemes = ["http"]
    consumes = ["json"]
    produces = ["json"]
    hosts = ["http://streams.dynamodb.amazonaws.com"]
    topics = ["cloud"]

[[backends]]
  group = "amazon-dynamodb-streams-2012-08-10"
  url_pattern = "/#ListStreams"
  method = "POST"
  encoding = "json"
  host = ["http://streams.dynamodb.amazonaws.com"]
  concurrent_calls = 1
  [backends.extra_config]
    provider = "amazonaws.com"
    description = "<fullname>Amazon DynamoDB</fullname> <p>Amazon DynamoDB Streams provides API actions for accessing streams and processing stream records. To learn more about application development with Streams, see <a href=\"http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Streams.html\">Capturing Table Activity with DynamoDB Streams</a> in the Amazon DynamoDB Developer Guide.</p>"
    version = "2012-08-10"
    slug = "amazon-dynamodb-streams-2012-08-10-liststreams"
    schemes = ["http"]
    consumes = ["json"]
    produces = ["json"]
    hosts = ["http://streams.dynamodb.amazonaws.com"]
    topics = ["cloud"]

[[backends]]
  group = "amazon-dynamodb-streams-2012-08-10"
  url_pattern = "/"
  method = "POST"
  encoding = "json"
  host = ["http://streams.dynamodb.amazonaws.com"]
  concurrent_calls = 1
  [backends.extra_config]
    provider = "amazonaws.com"
    description = "<fullname>Amazon DynamoDB</fullname> <p>Amazon DynamoDB Streams provides API actions for accessing streams and processing stream records. To learn more about application development with Streams, see <a href=\"http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Streams.html\">Capturing Table Activity with DynamoDB Streams</a> in the Amazon DynamoDB Developer Guide.</p>"
    version = "2012-08-10"
    slug = "amazon-dynamodb-streams-2012-08-10"
    schemes = ["http"]
    consumes = ["json"]
    produces = ["json"]
    hosts = ["http://streams.dynamodb.amazonaws.com"]
    topics = ["cloud"]
