[[backends]]
  group = "geographic-1-0-0"
  url_pattern = "/svc/semantic/v2/geocodes/query"
  method = "JSON"
  encoding = "json"
  host = ["https://api.nytimes.com"]
  concurrent_calls = 1
  [backends.extra_config]
    provider = "nytimes.com"
    description = "The Geographic API extends the Semantic API, using a linked data approach to enhance location concepts used in The New York Times' controlled vocabulary and data resources which combine them with the GeoNames database, an authoritative and free to use database of global geographical places, names and features.\n"
    version = "1.0.0"
    slug = "geographic-1-0-0-svc-semantic-v2-geocodes-query"
    schemes = ["http", "https"]
    produces = ["json"]
    hosts = ["http://api.nytimes.com", "https://api.nytimes.com"]
    topics = ["media", "open-data"]
