[[backends]]
  group = "azure-ml-commitment-plans-management-client-2016-05-01-preview"
  url_pattern = "/subscriptions/{subscriptionId}/providers/Microsoft"
  method = "MACHINELEARNING/COMMITMENTPLANS"
  encoding = "json"
  host = ["https://management.azure.com"]
  concurrent_calls = 1
  [backends.extra_config]
    provider = "azure.com"
    description = "These APIs allow end users to operate on Azure Machine Learning Commitment Plans resources and their child Commitment Association resources. They support CRUD operations for commitment plans, get and list operations for commitment associations, moving commitment associations between commitment plans, and retrieving commitment plan usage history."
    version = "2016-05-01-preview"
    slug = "azure-ml-commitment-plans-management-client-2016-05-01-preview-subscriptions-subscriptionid-providers-microsoft"
    schemes = ["https"]
    consumes = ["json"]
    produces = ["json"]
    hosts = ["https://management.azure.com"]
    topics = ["machine-learning"]

[[backends]]
  group = "azure-ml-commitment-plans-management-client-2016-05-01-preview"
  url_pattern = "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft"
  method = "MACHINELEARNING/COMMITMENTPLANS"
  encoding = "json"
  host = ["https://management.azure.com"]
  concurrent_calls = 1
  [backends.extra_config]
    provider = "azure.com"
    description = "These APIs allow end users to operate on Azure Machine Learning Commitment Plans resources and their child Commitment Association resources. They support CRUD operations for commitment plans, get and list operations for commitment associations, moving commitment associations between commitment plans, and retrieving commitment plan usage history."
    version = "2016-05-01-preview"
    slug = "azure-ml-commitment-plans-management-client-2016-05-01-preview-subscriptions-subscriptionid-resourcegroups-resourcegroupname-providers-microsoft"
    schemes = ["https"]
    consumes = ["json"]
    produces = ["json"]
    hosts = ["https://management.azure.com"]
    topics = ["machine-learning"]
