[[backends]]
  group = "recoveryservicesbackupclient-2016-12-01"
  url_pattern = "/Subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft"
  method = "RECOVERYSERVICES/VAULTS/{VAULTNAME}/BACKUPCONFIG/VAULTCONFIG"
  encoding = "json"
  host = ["https://management.azure.com"]
  concurrent_calls = 1
  [backends.extra_config]
    provider = "azure.com"
    version = "2016-12-01"
    slug = "recoveryservicesbackupclient-2016-12-01-subscriptions-subscriptionid-resourcegroups-resourcegroupname-providers-microsoft"
    schemes = ["https"]
    consumes = ["json"]
    produces = ["json"]
    hosts = ["https://management.azure.com"]
    topics = ["cloud"]
