[[backends]]
  group = "language-detection-apis-0-0-1"
  url_pattern = "/api/22/langdetect/get"
  method = "GET"
  encoding = "json"
  host = ["https://api.apitore.com"]
  whitelist = ["endTime", "language", "log", "probabilities", "processTime", "startTime", "text"]
  concurrent_calls = 1
  [backends.extra_config]
    provider = "apitore.com"
    description = "Language detection.<BR />[Endpoint] https://api.apitore.com/api/22"
    version = "0.0.1"
    slug = "language-detection-apis-0-0-1-api-22-langdetect-get"
    schemes = ["https"]
    consumes = ["json"]
    produces = ["json"]
    hosts = ["https://api.apitore.com"]
    topics = ["text"]
    [backends.extra_config.mapping]
      endTime = "endTime"
      language = "language"
      log = "log"
      probabilities = "probabilities"
      processTime = "processTime"
      startTime = "startTime"
      text = "text"

[[backends]]
  group = "language-detection-apis-0-0-1"
  url_pattern = "/api/22/langdetect/short/get"
  method = "GET"
  encoding = "json"
  host = ["https://api.apitore.com"]
  whitelist = ["endTime", "language", "log", "probabilities", "processTime", "startTime", "text"]
  concurrent_calls = 1
  [backends.extra_config]
    provider = "apitore.com"
    description = "Language detection.<BR />[Endpoint] https://api.apitore.com/api/22"
    version = "0.0.1"
    slug = "language-detection-apis-0-0-1-api-22-langdetect-short-get"
    schemes = ["https"]
    consumes = ["json"]
    produces = ["json"]
    hosts = ["https://api.apitore.com"]
    topics = ["text"]
    [backends.extra_config.mapping]
      endTime = "endTime"
      language = "language"
      log = "log"
      probabilities = "probabilities"
      processTime = "processTime"
      startTime = "startTime"
      text = "text"
