[[backends]]
  group = "top-stories-2-0-0"
  url_pattern = "/svc/topstories/v2/{section}"
  method = "{FORMAT}"
  encoding = "json"
  host = ["https://api.nytimes.com"]
  concurrent_calls = 1
  [backends.extra_config]
    provider = "nytimes.com"
    description = "The Top Stories API provides lists of articles and associated images by section."
    version = "2.0.0"
    slug = "top-stories-2-0-0-svc-topstories-v2-section"
    schemes = ["http", "https"]
    produces = ["json"]
    hosts = ["http://api.nytimes.com", "https://api.nytimes.com"]
    topics = ["media", "open-data"]
