[[backends]]
  group = "computemanagementclient-2016-04-30-preview"
  url_pattern = "/subscriptions/{subscriptionId}/providers/Microsoft"
  method = "COMPUTE/IMAGES"
  encoding = "json"
  host = ["https://management.azure.com"]
  concurrent_calls = 1
  [backends.extra_config]
    provider = "azure.com"
    description = "The Compute Management Client."
    version = "2016-04-30-preview"
    slug = "computemanagementclient-2016-04-30-preview-subscriptions-subscriptionid-providers-microsoft"
    schemes = ["https"]
    consumes = ["json"]
    produces = ["json"]
    hosts = ["https://management.azure.com"]
    topics = ["cloud"]

[[backends]]
  group = "computemanagementclient-2016-04-30-preview"
  url_pattern = "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft"
  method = "COMPUTE/AVAILABILITYSETS"
  encoding = "json"
  host = ["https://management.azure.com"]
  concurrent_calls = 1
  [backends.extra_config]
    provider = "azure.com"
    description = "The Compute Management Client."
    version = "2016-04-30-preview"
    slug = "computemanagementclient-2016-04-30-preview-subscriptions-subscriptionid-resourcegroups-resourcegroupname-providers-microsoft"
    schemes = ["https"]
    consumes = ["json"]
    produces = ["json"]
    hosts = ["https://management.azure.com"]
    topics = ["cloud"]
