[[backends]]
  group = "searchmanagementclient-2015-08-19"
  url_pattern = "/subscriptions/{subscriptionId}/providers/Microsoft"
  method = "SEARCH/CHECKNAMEAVAILABILITY"
  encoding = "json"
  host = ["https://management.azure.com"]
  concurrent_calls = 1
  [backends.extra_config]
    provider = "azure.com"
    description = "Client that can be used to manage Azure Search services and API keys."
    version = "2015-08-19"
    slug = "searchmanagementclient-2015-08-19-subscriptions-subscriptionid-providers-microsoft"
    schemes = ["https"]
    consumes = ["json", "json"]
    produces = ["json", "json"]
    hosts = ["https://management.azure.com"]
    topics = ["search"]

[[backends]]
  group = "searchmanagementclient-2015-08-19"
  url_pattern = "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft"
  method = "SEARCH/SEARCHSERVICES"
  encoding = "json"
  host = ["https://management.azure.com"]
  concurrent_calls = 1
  [backends.extra_config]
    provider = "azure.com"
    description = "Client that can be used to manage Azure Search services and API keys."
    version = "2015-08-19"
    slug = "searchmanagementclient-2015-08-19-subscriptions-subscriptionid-resourcegroups-resourcegroupname-providers-microsoft"
    schemes = ["https"]
    consumes = ["json", "json"]
    produces = ["json", "json"]
    hosts = ["https://management.azure.com"]
    topics = ["search"]
