[[backends]]
  group = "document-frequency-apis-0-0-1"
  url_pattern = "/api/16/documentfrequency/get"
  method = "GET"
  encoding = "json"
  host = ["https://api.apitore.com"]
  whitelist = ["documentFrequency", "endTime", "log", "processTime", "startTime", "word"]
  concurrent_calls = 1
  [backends.extra_config]
    provider = "apitore.com"
    description = "Document frequency of Wikipedia.<BR />[Endpoint] https://api.apitore.com/api/16"
    version = "0.0.1"
    slug = "document-frequency-apis-0-0-1-api-16-documentfrequency-get"
    schemes = ["https"]
    consumes = ["json"]
    produces = ["json"]
    hosts = ["https://api.apitore.com"]
    topics = ["text"]
    [backends.extra_config.mapping]
      documentFrequency = "documentFrequency"
      endTime = "endTime"
      log = "log"
      processTime = "processTime"
      startTime = "startTime"
      word = "word"
