[[backends]]
  group = "manufacturer-center-v1"
  url_pattern = "/v1/{parent}/products"
  method = "GET"
  host = ["https://manufacturers.googleapis.com"]
  url_keys = ["parent"]
  query_string_params = ["pageSize", "pageToken"]
  whitelist = ["nextPageToken", "products"]
  concurrent_calls = 1
  [backends.extra_config]
    provider = "googleapis.com"
    description = "Public API for managing Manufacturer Center related data."
    version = "v1"
    slug = "manufacturer-center-v1-v1-parent-products"
    schemes = ["https"]
    hosts = ["https://manufacturers.googleapis.com"]
    topics = ["accounts"]
    [backends.extra_config.mapping]
      nextPageToken = "nextPageToken"
      products = "products"

[[backends]]
  group = "manufacturer-center-v1"
  url_pattern = "/v1/{parent}/products/{name}"
  method = "GET"
  host = ["https://manufacturers.googleapis.com"]
  url_keys = ["name", "parent"]
  whitelist = ["contentLanguage", "issues", "manuallyDeletedAttributes", "name", "parent", "productId", "targetCountry"]
  concurrent_calls = 1
  [backends.extra_config]
    provider = "googleapis.com"
    description = "Public API for managing Manufacturer Center related data."
    version = "v1"
    slug = "manufacturer-center-v1-v1-parent-products-name"
    schemes = ["https"]
    hosts = ["https://manufacturers.googleapis.com"]
    topics = ["accounts"]
    [backends.extra_config.mapping]
      contentLanguage = "contentLanguage"
      issues = "issues"
      manuallyDeletedAttributes = "manuallyDeletedAttributes"
      name = "name"
      parent = "parent"
      productId = "productId"
      targetCountry = "targetCountry"
